### ISSUE TITLE
Cake for Visual Studio (2017) always crash during build.cake edit

### ISSUE THREAD

**Issue by MonDeveloper** [cake-build/cake-vs#77] opened 2017-09-11 21:50 UTC
Version
0.2.0.0
Last updated
7/9/2017, 05:32:23
Publisher
Cake Build

**Comment by donamk** [comment] 2018-02-13 03:55
Same here :(

**Comment by agc93** [comment] 2019-03-21 19:53
Thanks for reporting @MonDeveloper and @donamk !

To reproduce this, I'd definitely need a bit more information on what specifically is causing this.

First, if possible, it would be best if you can test with our [latest prerelease version](https://cakebuild.net/blog/2016/12/cake-vs-prerelease) as there's been quite a few "under the hood" improvements to how the extension works.

If it still causes crashes, would you be able to share the `.cake` file that causes this?

**Comment by gep13** [comment] 2020-12-15 20:06
I am going to go ahead and close this out, since this hasn't had a response.

If this is still an issue, please let us know.

**Closed by gep13** 2020-12-15 20:06 UTC
