### ISSUE TITLE
Cake Tasks in a Solution Folder aren't listed in the Task Runner Explorer

### ISSUE THREAD

**Issue by RavinduL** [cake-build/cake-vs#80] opened 2017-10-26 11:02 UTC
I've got a .NET Standard class library project with the following structure,

```
src/
│
├───Cake/
│   ├───tools/
│   ├───build.cake
│   ├───build.ps1
│   └───cake.config
│
├───Project/
│   └───Project.csproj
│
├───Project.Tests/
│   └───Project.Tests.csproj
│
└───Project.sln
```

The Cake build scripts located within the `src/Cake/` folder are added to the `Project.sln` solution within a Solution Folder (right click solution -> Add -> New Solution Folder), so that the Solution Explorer shows this (I've redacted some information),

![Solution Explorer](https://user-images.githubusercontent.com/7352580/32049413-954a8956-ba6a-11e7-836a-57e8319118e0.png)

With this project layout, the Task Runner Explorer doesn't list the tasks declared in `build.cake`.

![Task Runner Explorer](https://user-images.githubusercontent.com/7352580/32049596-3b67e7d4-ba6b-11e7-9acb-b9f5aac8f801.png)

**Comment by gep13** [comment] 2017-10-26 11:58
@RavinduL unfortunately, you are running into a known limitation of Visual Studio.  This is detailed in this issue:

https://github.com/cake-build/cake-vs/issues/30#issuecomment-251945464

I am going to close this as it is a duplicate of the other.

**Closed by gep13** 2017-10-26 11:58 UTC
Labels: Duplicate

**Comment by RavinduL** [comment] 2017-10-26 21:01
Thanks for your reply @gep13. @agc93's solution worked perfectly...

I resolved this by adding two files, `build.cake` and `cake.config` to the root of the `Project`.

`build.cake` contained,
```
#load "../Cake/build.cake"
```

`cake.config` contained,
```
[Paths]
Tools=../Cake/tools
```

**Comment by gep13** [comment] 2017-10-26 21:15
@RavinduL glad to hear that you got this working!  Thanks for reporting back!
